/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastaneotomasyonu;

import Class.Kullanıcı.Helper;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import hastaneotomasyonu.baglantı.*;
import java.beans.Statement;
import java.sql.*;
/**
 *
 * @author CENE
 */
public class Login extends javax.swing.JPanel {
    private baglantı con  = new baglantı();
    
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        vtnds_tc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hst_tc = new javax.swing.JTextField();
        kyt_btn = new javax.swing.JButton();
        grs_btn = new javax.swing.JButton();
        hst_psw = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dktr_tc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dktr_grs = new javax.swing.JButton();
        dktr_psw = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 204, 102));
        setToolTipText("");
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("      LOGO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 90, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("      HASTANE SİSTEMİ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 250, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vtnds_tc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        vtnds_tc.setText(" Kimlik Numaranız:");
        jPanel1.add(vtnds_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Hastane Şifreniz:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        hst_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hst_tcActionPerformed(evt);
            }
        });
        jPanel1.add(hst_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, -1));

        kyt_btn.setBackground(new java.awt.Color(204, 255, 51));
        kyt_btn.setText("KAYIT");
        jPanel1.add(kyt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 60));

        grs_btn.setBackground(new java.awt.Color(255, 102, 51));
        grs_btn.setText("GİRİŞ");
        jPanel1.add(grs_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 210, 60));

        hst_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hst_pswActionPerformed(evt);
            }
        });
        jPanel1.add(hst_psw, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 220, -1));

        jTabbedPane2.addTab(" VATANDAŞ GİRİŞİ", jPanel1);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText(" Kimlik Numaranız:");

        dktr_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dktr_tcActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Şifre          :  ");

        dktr_grs.setBackground(new java.awt.Color(255, 102, 51));
        dktr_grs.setText("GİRİŞ");
        dktr_grs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dktr_grsActionPerformed(evt);
            }
        });

        dktr_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dktr_pswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dktr_psw))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dktr_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dktr_grs, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dktr_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dktr_psw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(dktr_grs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("DOKTOR GİRİŞİ", jPanel2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 560, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void hst_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hst_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hst_tcActionPerformed

    private void dktr_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dktr_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dktr_tcActionPerformed

    private void dktr_grsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dktr_grsActionPerformed
        Verıtabanı verıtabanı = new Verıtabanı();
        verıtabanı.VerıAlma();
      
        
          
        
    }//GEN-LAST:event_dktr_grsActionPerformed

    private void dktr_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dktr_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dktr_pswActionPerformed

    private void hst_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hst_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hst_pswActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dktr_grs;
    private javax.swing.JPasswordField dktr_psw;
    private javax.swing.JTextField dktr_tc;
    private javax.swing.JButton grs_btn;
    private javax.swing.JPasswordField hst_psw;
    private javax.swing.JTextField hst_tc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton kyt_btn;
    private javax.swing.JLabel vtnds_tc;
    // End of variables declaration//GEN-END:variables
}
